const schema = {
  bsonType: "object",
  additionalProperties: false,
  title: "part",
  required: ["partno", "name", "vendor", "count", "location", "category"],
  properties: {
    _id: { bsonType: "objectId" },
    name: { bsonType: "string" },
    partno: { bsonType: "string" },
    vendor: { bsonType: "string" },
    count: { bsonType: "number" },
    location: { bsonType: "string" },
    sublocation: { bsonType: "string" },
    description: { bsonType: "string" },
    serialno: { bsonType: "string" },
    category: { bsonType: "string" },
    subcategory: { bsonType: "string" },
    notes: { bsonType: "string" },
  },
};
